sudo: false
install: true

language: java

notifications:
  email:
    recipients:
      - devcenter@docusign.com
    on_success: never
    on_failure: change

jdk:
  - oraclejdk8

script: mvn clean package
